DELETE FROM users;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM comments;

ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE bookings ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE items ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE comments ALTER COLUMN ID RESTART WITH 1;